stages:
  - stage: test
    displayName: Test
    jobs:
      - template: ci/cargo-job-per-channel-target.yml
        parameters:
          channels: [ nightly ]
          targets:
            - target: 'i686-pc-windows-msvc'
            - target: 'i686-pc-windows-msvc'
              channels: [ stable ]
              cargoSteps:
                - bash: $CARGO test --target $TARGET --no-default-features
                  displayName: Cargo test
            - target: 'x86_64-pc-windows-msvc'
            # - target: 'i686-pc-windows-gnu'
            - target: 'x86_64-pc-windows-gnu'
            # - target: 'i686-apple-darwin'
            - target: 'x86_64-apple-darwin'
              preSteps:
                - script: cp ./ci/macos/* ~/.cargo
                  displayName: Configure custom linker
            - target: 'i686-unknown-linux-gnu'
              preSteps:
                - script: sudo apt-get update && sudo apt-get install gcc-multilib
                  displayName: Install GCC 32-bit libs
            - target: 'x86_64-unknown-linux-gnu'
            - target: 'x86_64-unknown-linux-gnu'
              channels: [ stable ]
              cargoSteps:
                - bash: $CARGO test --target $TARGET --no-default-features
                  displayName: Cargo test
            # - target: 'x86_64-unknown-linux-musl'
            #   cross: true
